import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono } from "next/font/google";
import { Header } from "@/components/shared/header/Header";
import { Toaster } from "@/components/ui/sonner";

const geistMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`dark antialiased ${geistMono.className}`}>
				<Header />
				<div className="flex min-h-screen w-full justify-center px-6 md:px-0">
					<div className="w-full max-w-7xl">{children}</div>
				</div>
				<Toaster richColors position="top-center" />
			</body>
		</html>
	);
}
